# Generated by Django 2.2.3 on 2019-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(db_index=True, max_length=50)),
                ('unit', models.CharField(db_index=True, max_length=10)),
                ('resource', models.IntegerField(choices=[(1, 'Electricity'), (2, 'Water'), (3, 'Gas')])),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
