# Generated by Django 2.2.3 on 2019-08-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(null=True)),
                ('value', models.FloatField(default=0)),
                ('consumption', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(db_index=True, max_length=50)),
                ('unit', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('resource', models.CharField(choices=[('E', 'Electricity'), ('W', 'Water'), ('G', 'Gas')], max_length=2)),
            ],
        ),
    ]
