# Generated by Django 2.2.3 on 2019-08-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meter.Meter'),
        ),
    ]
