# Generated by Django 2.2.3 on 2019-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_auto_20190727_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='resource',
            field=models.IntegerField(choices=[(1, 'Electricity'), (2, 'Water'), (3, 'Gas')]),
        ),
    ]
