# Generated by Django 2.2.3 on 2019-07-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0003_auto_20190727_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='resource',
            field=models.CharField(choices=[('E', 'Electricity'), ('W', 'Water'), ('G', 'Gas')], max_length=2),
        ),
    ]
