# Generated by Django 2.2.3 on 2019-07-28 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_auto_20190727_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
